name: Deploy via CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create deployment bundle
        run: zip -r app.zip app appspec.yml scripts

      - name: Upload to S3
        run: aws s3 cp app.zip s3://my-max-app-bucket/app-${{ github.run_number }}.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name MaxApp-app \
            --deployment-group-name MaxApp-dg \
            --s3-location bucket=my-max-app-bucket,bundleType=zip,key=app-${{ github.run_number }}.zip
